import {
  addWorkspaceVideo,
  createWorkspaceFolder,
  deleteWorkspaceFolder,
  deleteWorkspaceVideo,
  getWorkspaceFolder,
  getWorkspaceFolders,
  getFacebookWorkspaceFolders,
  createFacebookWorkspaceFolder,
  getFacebookWorkspaceFolder,
  deleteFacebookWorkspaceFolder,
  addFacebookWorkspaceVideo,
  deleteFacebookWorkspaceVideo,
  getInstagramWorkspaceFolders,
  createInstagramWorkspaceFolder,
  getInstagramWorkspaceFolder,
  deleteInstagramWorkspaceFolder,
  addInstagramWorkspaceVideo,
  deleteInstagramWorkspaceVideo,
} from '../../lib/api.js';

export const PLATFORM_WORKSPACE = {
  tiktok: {
    platform: 'tiktok',
    label: 'TikTok',
    basePath: '/tiktok/workspace',
    urlField: 'tiktok_url',
    description: 'Save TikTok links in folders to review and play later.',
    linkPlaceholder: 'https://www.tiktok.com/@user/video/123...',
    addModalTitle: 'Add TikTok video',
    addModalHelp: 'Paste a public TikTok video link to save it in this folder.',
    openExternalLabel: 'Open on TikTok',
    searchFoldersPlaceholder: 'Search folders…',
    searchItemsPlaceholder: 'Search by title, @username, or link…',
    api: {
      getFolders: getWorkspaceFolders,
      createFolder: createWorkspaceFolder,
      getFolder: getWorkspaceFolder,
      deleteFolder: deleteWorkspaceFolder,
      addVideo: addWorkspaceVideo,
      deleteVideo: deleteWorkspaceVideo,
    },
  },
  facebook: {
    platform: 'facebook',
    label: 'Facebook',
    basePath: '/facebook/workspace',
    urlField: 'facebook_url',
    description: 'Save Facebook post and video links in folders to review later.',
    linkPlaceholder: 'https://www.facebook.com/...',
    addModalTitle: 'Add Facebook link',
    addModalHelp: 'Paste a public Facebook post or video link.',
    openExternalLabel: 'Open on Facebook',
    searchFoldersPlaceholder: 'Search folders…',
    searchItemsPlaceholder: 'Search by title, page, or link…',
    api: {
      getFolders: getFacebookWorkspaceFolders,
      createFolder: createFacebookWorkspaceFolder,
      getFolder: getFacebookWorkspaceFolder,
      deleteFolder: deleteFacebookWorkspaceFolder,
      addVideo: addFacebookWorkspaceVideo,
      deleteVideo: deleteFacebookWorkspaceVideo,
    },
  },
  instagram: {
    platform: 'instagram',
    label: 'Instagram',
    basePath: '/instagram/workspace',
    urlField: 'instagram_url',
    description: 'Save Instagram post and reel links in folders to review later.',
    linkPlaceholder: 'https://www.instagram.com/p/... or /reel/...',
    addModalTitle: 'Add Instagram link',
    addModalHelp: 'Paste a public Instagram post or reel link.',
    openExternalLabel: 'Open on Instagram',
    searchFoldersPlaceholder: 'Search folders…',
    searchItemsPlaceholder: 'Search by title, @username, or link…',
    api: {
      getFolders: getInstagramWorkspaceFolders,
      createFolder: createInstagramWorkspaceFolder,
      getFolder: getInstagramWorkspaceFolder,
      deleteFolder: deleteInstagramWorkspaceFolder,
      addVideo: addInstagramWorkspaceVideo,
      deleteVideo: deleteInstagramWorkspaceVideo,
    },
  },
};

export function getPlatformWorkspaceConfig(platform) {
  return PLATFORM_WORKSPACE[platform] || PLATFORM_WORKSPACE.tiktok;
}
